name: TPS verify

on:
  push:
    branches:
      - '**'
    paths:
      - 'p*/**'
  workflow_dispatch:
    inputs:
      problems:
        description: 'Problem labels to verify'
  

jobs:
  run:
    uses: tobiichi3227/tps-actions/.github/workflows/tps-verify.yml@main
    with:
      problems: ${{ github.event.inputs.problems }}
      runs-on: 'self-hosted'
